
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/yourorg/infractl/internal/tui"


)

var tests = []testing.InternalTest{

	{"TestInitialWindowSizeCmdFallsBackToDefault", _test.TestInitialWindowSizeCmdFallsBackToDefault},

	{"TestToolDisplayNameUsesShellForShellExec", _test.TestToolDisplayNameUsesShellForShellExec},

	{"TestToolTargetLabelShowsLocalShellContext", _test.TestToolTargetLabelShowsLocalShellContext},

	{"TestToolTargetLabelShowsRemoteShellContext", _test.TestToolTargetLabelShowsRemoteShellContext},

	{"TestFormatPastedTextRef", _test.TestFormatPastedTextRef},

	{"TestExpandPastedTextRefs", _test.TestExpandPastedTextRefs},

	{"TestExpandPastedTextRefsSkipsMissingContent", _test.TestExpandPastedTextRefsSkipsMissingContent},

	{"TestMaybeTruncateDisplayInput", _test.TestMaybeTruncateDisplayInput},

	{"TestNormalizePastedText", _test.TestNormalizePastedText},

	{"TestSelectionViewOmitsDefaultHeaderWhenEmpty", _test.TestSelectionViewOmitsDefaultHeaderWhenEmpty},

	{"TestSelectionViewShowsExplicitHeader", _test.TestSelectionViewShowsExplicitHeader},

	{"TestSelectionTextInputOmitsDefaultHeaderWhenEmpty", _test.TestSelectionTextInputOmitsDefaultHeaderWhenEmpty},

	{"TestBuildRoundedBorderTitleLineKeepsTitleAndCorners", _test.TestBuildRoundedBorderTitleLineKeepsTitleAndCorners},

	{"TestVisibleShellBoxUsesLatestCompletedShellWhenIdle", _test.TestVisibleShellBoxUsesLatestCompletedShellWhenIdle},

	{"TestVisibleShellBoxPrefersRunningShellOverHistory", _test.TestVisibleShellBoxPrefersRunningShellOverHistory},

	{"TestShellTaskLabelHidesRawCommandForShellExec", _test.TestShellTaskLabelHidesRawCommandForShellExec},

	{"TestRenderShellBoxRunningShowsTotalAndLatestTenLines", _test.TestRenderShellBoxRunningShowsTotalAndLatestTenLines},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/yourorg/infractl"
	testdeps.ImportPath = "github.com/yourorg/infractl/internal/tui"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

