
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/yourorg/infractl/internal/agent"


)

var tests = []testing.InternalTest{

	{"TestResolveStoredPasswordByTargetName", _test.TestResolveStoredPasswordByTargetName},

	{"TestResolveStoredPasswordByHostPrompt", _test.TestResolveStoredPasswordByHostPrompt},

	{"TestSmartIdleInputHandler_AbortsOnDatabaseREPLPrompt", _test.TestSmartIdleInputHandler_AbortsOnDatabaseREPLPrompt},

	{"TestIdleDetectExecutorPreservesPersistentSessions", _test.TestIdleDetectExecutorPreservesPersistentSessions},

	{"TestDetectIdleInputHintForHereDoc", _test.TestDetectIdleInputHintForHereDoc},

	{"TestDetectIdleInputHintWithoutHereDoc", _test.TestDetectIdleInputHintWithoutHereDoc},

	{"TestAppendLocalControllerContextWindowsUsesPowerShellGuidance", _test.TestAppendLocalControllerContextWindowsUsesPowerShellGuidance},

	{"TestAppendContextGuardrailsIncludesSessionContextRule", _test.TestAppendContextGuardrailsIncludesSessionContextRule},

	{"TestAppendSafetyRulesIncludeHereDocGuidance", _test.TestAppendSafetyRulesIncludeHereDocGuidance},

	{"TestResolveClientForTierRoutesReasoningTier", _test.TestResolveClientForTierRoutesReasoningTier},

	{"TestResolveClientForTierRoutesFastTier", _test.TestResolveClientForTierRoutesFastTier},

	{"TestResolveClientForTierFallsBackToGeneralWhenMissing", _test.TestResolveClientForTierFallsBackToGeneralWhenMissing},

	{"TestResolveClientForTierDefaultsToGeneralForUnknownTier", _test.TestResolveClientForTierDefaultsToGeneralForUnknownTier},

	{"TestResolveClientForTierUsesLLMClientWithoutRegistry", _test.TestResolveClientForTierUsesLLMClientWithoutRegistry},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/yourorg/infractl"
	testdeps.ImportPath = "github.com/yourorg/infractl/internal/agent"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

