
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/yourorg/infractl/internal/tools"


)

var tests = []testing.InternalTest{

	{"TestAskUserQuestionToolExecuteFreeTextQuestion", _test.TestAskUserQuestionToolExecuteFreeTextQuestion},

	{"TestAskUserQuestionToolExecuteSelectQuestion", _test.TestAskUserQuestionToolExecuteSelectQuestion},

	{"TestAskUserQuestionToolExecuteInvalidOptionCount", _test.TestAskUserQuestionToolExecuteInvalidOptionCount},

	{"TestBuildReadCommandLocalWindowsUsesRawPowerShell", _test.TestBuildReadCommandLocalWindowsUsesRawPowerShell},

	{"TestBuildReadCommandRemoteWindowsUsesEncodedPowerShell", _test.TestBuildReadCommandRemoteWindowsUsesEncodedPowerShell},

	{"TestBuildBackupCommandRemoteWindowsUsesEncodedPowerShell", _test.TestBuildBackupCommandRemoteWindowsUsesEncodedPowerShell},

	{"TestServerRemoveToolClearsRuntimeAndActiveServer", _test.TestServerRemoveToolClearsRuntimeAndActiveServer},

	{"TestServerRemoveToolStopsOnConnectorCleanupFailure", _test.TestServerRemoveToolStopsOnConnectorCleanupFailure},

	{"TestSessionContextToolReportsLocalControllerDefaults", _test.TestSessionContextToolReportsLocalControllerDefaults},

	{"TestSessionContextToolReportsActiveServerContext", _test.TestSessionContextToolReportsActiveServerContext},

	{"TestShellExecToolPrefixesExecutionContextForLocalRuns", _test.TestShellExecToolPrefixesExecutionContextForLocalRuns},

	{"TestShellExecToolPrefixesExecutionContextForRemoteRuns", _test.TestShellExecToolPrefixesExecutionContextForRemoteRuns},

	{"TestShellExecToolDescriptionEncouragesNonInteractiveCommands", _test.TestShellExecToolDescriptionEncouragesNonInteractiveCommands},

	{"TestShellExecToolCachesPrivilegePasswordInMemory", _test.TestShellExecToolCachesPrivilegePasswordInMemory},

	{"TestShellExecToolReusesRootSessionForBecomeUser", _test.TestShellExecToolReusesRootSessionForBecomeUser},

	{"TestShellExecToolRetriesPlainPermissionFailureWithRootSession", _test.TestShellExecToolRetriesPlainPermissionFailureWithRootSession},

	{"TestVerifyCompleteTool_Execute_Validation", _test.TestVerifyCompleteTool_Execute_Validation},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/yourorg/infractl"
	testdeps.ImportPath = "github.com/yourorg/infractl/internal/tools"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

